name: Make_All
on: [push, pull_request, workflow_dispatch]
jobs:
  Make_All:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2  
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.21
          packages: >
            curl
            lua
            lua-socket
            discount
            vim
            weasyprint
      - name: Build all
        run: mkdir -p ./build ; lua5.4 "./util/fw_extract.lua"
        shell: alpine.sh {0}
        
      - uses: actions/checkout@v2
      - run: echo "TAG_NAME=v0.1-rc" >> "$GITHUB_OUTPUT"
        id: version_check
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.version_check.outputs.TAG_NAME}}
          files: |
             build/fantasy_world_en.pdf
             build/fantasy_world_en.html
             build/fantasy_world_ita.pdf
             build/fantasy_world_ita.html
             build/the_world.html
             build/the_world.pdf

