name: Make_All
on: [push, pull_request, workflow_dispatch]
jobs:
  Make_All:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install lua5.3 lua-socket weasyprint discount vim
          sudo apt-get purge weasyprint
      - run: PATH="./:$PATH" PYTHONPATH="./WeasyPrint-60.2:./pydyf-0.8.0:$PYTHONPATH" lua ./make.lua
      - run: echo "TAG_NAME=v0.1-rc" >> "$GITHUB_OUTPUT"
        id: version_check
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.version_check.outputs.TAG_NAME}}
          files: |
             build/fantasy_world_en.pdf
             build/fantasy_world_en.html
             build/fantasy_world_ita.pdf
             build/fantasy_world_ita.html
             build/the_world.html
             build/the_world.pdf

